### PR TITLE
fix(filter): Handle reset filter

### LINKED ISSUE #149: BUG(Filter): Error server when change filter type
### Describe the bug
When changing filter type, an error occurs on the server due to incorrect values being used.
image

### Steps to reproduce
1. Add advanced filter (ex: `Due Date`)
2. Select Date (ex: `today`)
3. Change to other filter type (ex: `Assignee`)

### PR DESCRIPTION
**Pull request by Us3r-gitHub**
Fixes #149

### CODE REVIEW

File: packages/frontend/src/components/project-management/views/BaseViewChipFilter/BaseViewChipFilterItem.vue [hunk 1]
```diff
@@ -14,7 +14,7 @@ const props = defineProps<{
   fields: FieldFilterOption[];
   users: User[];
 }>();
-const emit = defineEmits(['delete']);
+const emit = defineEmits(['filter:update:field', 'delete']);
```
Comment (MoShizzle) [inline packages/frontend/src/components/project-management/views/BaseViewChipFilter/BaseViewChipFilterItem.vue:17]: Is this emit used anywhere? I can't seem to find any use for it

Comment (Us3r-gitHub) [reply packages/frontend/src/components/project-management/views/BaseViewChipFilter/BaseViewChipFilterItem.vue:17]: I forget to remove it

**Review by MoShizzle — APPROVED** [review]
